"""Turning a run into the document a reader argues with.

Everything here is generated. No number in `RESULTS.md` is typed by hand, which is the only way to
keep a report honest across a dozen edits — a hand-copied figure is a figure that will eventually be
stale, and nobody will notice because it looks fine.

The layout is deliberate. Coverage at zero unsafe errors goes first because it is the headline, then
immediately the two things that stop it being a magic trick: the trivial baselines that reach it by
refusing to answer, and the false-abstention rate that shows what refusing costs.
"""

from __future__ import annotations

from dataclasses import dataclass

from caliper.evalrun import ArmReport
from caliper.metrics import CurvePoint


def _pct(value: float) -> str:
    return f"{value * 100:.0f}%"


def _ci(bounds: tuple[float, float]) -> str:
    return f"{_pct(bounds[0])}–{_pct(bounds[1])}"


def _cost(value: float | None) -> str:
    return "—" if value is None else f"${value:.2f}"


@dataclass(frozen=True)
class ReportInputs:
    arms: list[ArmReport]
    key_digest: str
    key_cases: int
    metamorphic: str | None = None
    changelog_note: str | None = None


def headline(arms: list[ArmReport]) -> str:
    caliper = next((a for a in arms if a.arm == "caliper"), None)
    baseline = next((a for a in arms if a.arm == "single_prompt"), None)
    if caliper is None:
        return "No Caliper arm was run."

    lines = [
        f"Caliper decided **{_pct(caliper.summary.coverage_at_zero_unsafe)}** of cases without a "
        "human while committing no unsafe error.",
    ]
    if baseline is not None:
        lines.append(
            f"The single-prompt baseline answered every case and committed "
            f"**{baseline.summary.unsafe}** unsafe errors out of {baseline.summary.cases}."
        )
    return " ".join(lines)


def arm_table(arms: list[ArmReport]) -> str:
    header = (
        "| Arm | Cases | Accuracy | 95% CI | Coverage | Unsafe errors | "
        "False abstention | Coverage at 0 unsafe | Cost |\n"
        "|---|---:|---:|---|---:|---:|---:|---:|---:|"
    )
    rows = []
    for report in arms:
        s = report.summary
        rows.append(
            f"| `{report.arm}` | {s.cases} | {_pct(s.accuracy)} | {_ci(s.accuracy_ci)} | "
            f"{_pct(s.coverage)} | {s.unsafe} | {_pct(s.false_abstention)} | "
            f"{_pct(s.coverage_at_zero_unsafe)} | {_cost(report.cost_usd)} |"
        )
    return "\n".join([header, *rows])


def curve_table(points: list[CurvePoint]) -> str:
    header = (
        "| Abstention threshold | Coverage | Selective risk | Unsafe errors | Cases answered |\n"
        "|---:|---:|---:|---:|---:|"
    )
    rows = [
        f"| {p.threshold:.2f} | {_pct(p.coverage)} | {_pct(p.risk)} | {p.unsafe} | {p.answered} |"
        for p in points
    ]
    return "\n".join([header, *rows])


def trap_table(arms: list[ArmReport]) -> str:
    traps = sorted({trap for a in arms for trap in a.summary.by_trap})
    header = "| Trap | " + " | ".join(f"`{a.arm}`" for a in arms) + " |\n|---|" + "---|" * len(arms)
    rows = []
    for trap in traps:
        cells = []
        for report in arms:
            slice_ = report.summary.by_trap.get(trap)
            cells.append(
                "—"
                if slice_ is None
                else f"{slice_.correct}/{slice_.cases} correct, {slice_.unsafe} unsafe"
            )
        rows.append(f"| `{trap}` | " + " | ".join(cells) + " |")
    return "\n".join([header, *rows])


def failures_section(arms: list[ArmReport]) -> str:
    lines = []
    for report in arms:
        if not report.failures:
            continue
        lines.append(f"**`{report.arm}`** — {len(report.failures)} case(s) failed to run:")
        lines += [f"- `{f.case_id}` at {f.stage}: {f.error}" for f in report.failures]
    if not lines:
        return "No case failed to run in any arm."
    return "\n".join(lines)


def render(inputs: ReportInputs) -> str:
    """Build `RESULTS.md` from the run."""
    caliper = next((a for a in inputs.arms if a.arm == "caliper"), None)
    sections = [
        "# Results",
        "",
        "Generated by `caliper report`. Every figure below comes from the committed run; none is "
        "typed by hand.",
        "",
        f"Answer key: **{inputs.key_cases} cases**, frozen before the first scored run, "
        f"digest `{inputs.key_digest[:16]}…`.",
        "",
        "## Headline",
        "",
        headline(inputs.arms),
        "",
        "At this sample size an exact binomial interval spans roughly thirteen percentage points. "
        "Differences narrower than that are not differences, and the intervals are printed so that "
        "is checkable rather than asserted.",
        "",
        "## Every arm",
        "",
        arm_table(inputs.arms),
        "",
        "`always_needs_review` is in this table on purpose. It commits no unsafe error at all and "
        "is useless, which is the whole reason coverage and false abstention are reported beside "
        "the safety number rather than behind it.",
        "",
    ]

    if caliper is not None and caliper.summary.curve:
        sections += [
            "## Risk and coverage",
            "",
            "Each row answers the cases whose criteria resolved at least this far, reading an "
            "unresolved criterion the way a system with no notion of abstention would: an unknown "
            "inclusion assumed met, an unknown exclusion assumed untriggered.",
            "",
            curve_table(caliper.summary.curve),
            "",
        ]

    sections += [
        "## By trap",
        "",
        "Cases are labelled by the specific failure they were built to provoke.",
        "",
        trap_table(inputs.arms),
        "",
        "## Cases that failed to run",
        "",
        failures_section(inputs.arms),
        "",
    ]

    if inputs.metamorphic:
        sections += [
            "## Metamorphic checks",
            "",
            "These assert a required relationship between two runs rather than an answer, so they "
            "are true by construction and owe nothing to our answer key.",
            "",
            inputs.metamorphic,
            "",
        ]

    if inputs.changelog_note:
        sections += [inputs.changelog_note, ""]

    return "\n".join(sections)
